### PR TITLE
HMS-1000-2T with serial 0x1410ffffffff

### PR DESCRIPTION
**Pull request by kindyy**
Add support for HMS-1000-2T with a serial starting with 0x1410

### CODE REVIEW

**Comment by tbnobody** [comment]
Please squash your commits into one and provide a proper commit message. Also please update the documentation in the inverter folder.

Or allow me to do the code changes (but in this case your name will not be visible in the version history)

**Comment by kindyy** [comment]
Yes, I'll let you handle it; I don't know Git yet.

**Comment by tbnobody** [comment]
Could you please open the Device Info Dialog: 
image
and check if your device is correctly shown?

**Comment by kindyy** [comment]
I don't have the Device Info Dialog for this inverter. I think I could do it when I have the modified file and I have upgraded my firmware. For now, my inverter is unknown.

**Comment by tbnobody** [comment]
But then I would suggest you update the file and test if it's work. I will not add a untested patch.

**Comment by kindyy** [comment]
I don't know how to generate the release that would allow me to update my esp with the modified file.

Is it possible to create the release in a beta branch that I can test and confirm?

**Comment by tbnobody** [comment]
which binary did you use to install your hardware? Without this information I cannot provide the right file for your MCU type.

**Comment by kindyy** [comment]
I used this version : generic_esp32

**Comment by tbnobody** [comment]
Please find attached the compiled file with your patch.

[generic_esp32.zip](https://github.com/user-attachments/files/16769589/generic_esp32.zip)

**Comment by kindyy** [comment]
image

It better now

**Comment by kindyy** [comment]
Hello,

I haven't noticed any errors since I applied the patch :

image

image

And MQTT is correctly returning all the information.

image

image

**Comment by tbnobody** [comment]
Thank you. Will add it in the next release

**Comment by elloupgarou** [comment]
Hello,

I'm back from vacation.

Can someone compile the patch for a generic_esp32s3_usb binary? So I can validate that it works for my case?

Thanks in advance.

**Comment by elloupgarou** [comment]
> Veuillez trouver ci-joint le fichier compilé avec votre correctif.
> 
> [generic_esp32.zip](https://github.com/user-attachments/files/16769589/generic_esp32.zip)
Bonjour ,

@tbnobody

Would it be possible to have the generic_esp32s3_usb binary with this modification?

Thanks in advance.

**Comment by tbnobody** [comment]
Already merged with 1f3af949a04c3288a37d4e9f303274e8c69af4a3

**Pull request closed without merging**
