### PR TITLE
NFC: Includes list: Remove unneeded PinMapping.h

### PR DESCRIPTION
**Pull request by StefanOberhumer**
Also: Sort include directives by name.

### CODE REVIEW

**Comment by tbnobody** [comment]
The `Pinmapping.h` can be removed, thats true. But the ordering is correct. The first include in the cpp file is always the corresponding header file (with the same name of the cpp file).

**Comment by StefanOberhumer** [comment]
> ... But the ordering is correct. The first ....

Ah - OK!
I usually include all of the "standards" (#include **<**XX**>**) first!
But thinking about ... Your approach makes more sense ! :+1: 

Will adapt ...

**Comment by tbnobody** [comment]
I've set the auto formatter style to `WebKit`. It sorts the corresponding header file at the first position followed by project specific headers and at least the global headers.

**Comment by StefanOberhumer** [comment]
The now diff says:
I just removed the unneeded '#include PinMapping.h'  and changed a comment!

Based on your explanation: That result should match the project requirements.

Btrw: THX having comprehensible/explicable project settings/requirements :+1:

**Comment by tbnobody** [comment]
Thank you and sorry for the nagging. I will include the PR in the next release.

**Pull request merged**
