### PR TITLE
Esp32 eth poe ecrow

### PR DESCRIPTION
**Pull request by khancyr**
Esp32 stick eth poe board support https://www.elecrow.com/esp32-stick-poe-a.html
Fix LilyGO_T_ETH_POE ETH pins

### CODE REVIEW

**Comment by tbnobody** [comment]
Please don't use this custom profiles. Instead create a device profile json. Several samples can be found here: <https://github.com/tbnobody/OpenDTU/tree/master/docs/DeviceProfiles>

**Comment by khancyr** [comment]
ok I will create a new profile for the esp32_stick_poe
For the Lily poe, the config is currently broken, do you prefer to keep the fix, or full removal as we got the custom profile ?

**Comment by tbnobody** [comment]
If it's broken then I would prefer removing it from the `platform.ini` and have a proper device profile instead.

**Comment by khancyr** [comment]
updated with profile.
One bad things on profiles is that we lost the comments line to find the board official docs. If we can have another field for this that would be great.

**Pull request merged**
