### PR TITLE
reworked the InverterAdminView.vue view for easier maintainability

### PR DESCRIPTION
**Pull request by noicet**
Reworking the view also fixed the bug of changed max_power values not being reset after canceling the edit modal. The input group layout has been changed a bit to allow for more than one input field per line later on.
The rework has been done in preparation for implementing a new feature where the user is able to set a ChannelName/StringName as well as a DisplayOrder.

### CODE REVIEW

**Comment by noicet** [comment]
Thank you for accepting the pull request (and for the project as a whole). Is it ok if I rework other views one by one in this manner, meaning non- or minimal-intrusive, with readability and "byte count" in mind?

**Comment by tbnobody** [comment]
Yes of cource. Simpler and more readable code is always good! 
Thats my first project using vue. Always good to learn something new :)

**Comment by mwilk-dev** [comment]
Defür schaut der Code doch gut aus. Ich hatte bereits einige vue-Projekte, eine gute Wahl für die zu erwartende Komplexität des Frontends :+1:

**Comment by noicet** [comment]
Dafür schaut der Code doch gut aus. Ich hatte bereits einige Projekte, vue war eine gute Wahl für die Komplexität, die zu erwarten ist. 👍

**Pull request merged**
