### PR TITLE
Add Spanish locale to the web

### PR DESCRIPTION
**Pull request by foroae**
Add Spanish locale to the web

### CODE REVIEW

**Comment by 3DJupp** [comment]
Yeah, one of the more sunnier countries. 🇪🇸 , but also 🇬🇷 , 🇵🇹 might be an option.

**Comment by tbnobody** [comment]
Please see https://github.com/tbnobody/OpenDTU/pull/1830#issuecomment-2051951742

This PR is not forgotten... Just working on another solution

**Comment by stefan123t** [comment]
@tbnobody as this other NLS solution may help tremendously to reduce the code and factor out the common language strings into some shared dictionary / JSON referenced by the Vue app:
Do you already have a working prototype or can we help already by providing these NLS / PO dictionary archives ?

**Comment by tbnobody** [comment]
Spanish language is implemented as a language pack

**Pull request closed without merging**
