### PR TITLE
use proper file handling

### PR DESCRIPTION
**Pull request by mpw96**
Just improving file handling:
- Close the file to read from immediately after reading,
- set encoding in open methods.

This actually fixes nothing, but makes the code [cleaner](https://refactoring.guru/refactoring/what-is-refactoring).

### CODE REVIEW

**Comment by tbnobody** [comment]
Please provide a proper description of this PR. It currently works as expected. Why do you want to change things?
Please also correct spelling mistakes.

**Comment by mpw96** [comment]
> Please also correct spelling mistakes.
I wanted to write "massage", because I'm massaging the code... ;-)

**Comment by mpw96** [comment]
@tbnobody If you don't like this change (and you are right that it fixes nothing) you can as well close this pull request. Thank you!

**Comment by mpw96** [comment]
@tbnobody I have updated the pull request title and the description to explain why I think this change makes sense (basically: yes, the existing code works, but it's not as short and as understandable as possible).

**Comment by mpw96** [comment]
@tbnobody This is just better python coding. It let's the library do the work. If you don't want it, please close the pull request, I'd of course be fine with it. Thank you!

**Pull request merged**
