### PR TITLE
fix typo: publish_invterval

### PR DESCRIPTION
**Pull request by morph027**

### CODE REVIEW

**Comment by tbnobody** [comment]
Unfortunatly it's not possible to just change this value. It would break all users installations and reset the value to the default. Have to implement a migration.

**Comment by morph027** [comment]
Ah, of course. I see. Any clue how to do this? I'm more the python guy 😀

**Comment by tbnobody** [comment]
Yes... will commit it in the next days...

**Comment by morph027** [comment]
Are you planning to include the fix? If so, we can just close this PR then.

**Comment by tbnobody** [comment]
Implemented in dc66a82695d37e6c15c38a91a26a4cf9cb51e9fd

**Pull request closed without merging**
